### PR TITLE
Incremental change merging from the 2020 pull request [part 3]

### PR DESCRIPTION
**Pull request by Oaphi**
In continuation of PRs #8 and #9, this PR reintroduces changes to the main module connecting all other updates (WIP).

### CODE REVIEW

**Comment by Oaphi** [comment]
I also think an update is needed to type definitions of the ChatExchage package - the constructor parameter `host` is defined as a TypeScript `enum` while [in reality](https://github.com/samliew/chatexchange/blob/master/src/Client.js) it is a string union causing TS to go bananas about this:  `const client = new Client(chatDomain);` since `chatDomain` is of type `string`.

**Comment by samliew** [comment]
Hey Oleg,

The previous maintainer of ChatExchange left and transferred me the repo,
but I'm not quite sure how to maintain it going forward. Would you like to
take over the project?

Sam

**Comment by Oaphi** [comment]
Heya @samliew,

sure, I can shape it up - I got the impression it was sort of abandoned and was in the middle of trying to find out which branch was used to publish the latest version of the package. Seems like it is the `typescript` one? This is the only thing I would like to clarify first - because as far as I understand it, the `master` branch is not the one used to publish the package (judging by all the d.ts files generated).

Do you think it is worth maintaining? Doesn't seem like it is used much. That said, I will probably end up doing the same thing as I am becoming more involved with userscripts/bots business on SO, so it is nice to have a working frame.

Cheers, Oleg

**Review by samliew — APPROVED** [review]
merge when ready

**Pull request merged**
