### PR TITLE
Helping in making the Election Bot even better

### PR DESCRIPTION
**Pull request by Oaphi**
Hi Samuel,

while watching this year's election, I noticed the link to the source code of your helpful bot and could not miss the opportunity to fork the repo and tinker around a bit, which resulted in this PR if you are interested in lifting some load off your shoulders regarding the bot development. PR introduces the following changes:

1. Added tests (Mocha + Chai) for timestamp formatting utilities and randomizable array methods
2. Modernized and linted part of the codebase (in part as I am nervous about changing parts not covered).
3. Moved word randomizer from an Array prototype method to a separate class (tested) and added a more robust method for extracting a random element from it.
4. Added random "modal" verb utility (used in "If you really {{modal}} know, your candidate score" only for now).
5. Started moving command actions to reusable utilities (for now - made "Welcome" message builder a `sayHI` utility).
6. "Parallelized" message resolving with `Promise.all` (`userName`, `userId` and `targetUserId` - the latter does so conditionally).
7. Added JSDoc comments where could (documentation-ready).

---

Updates in the meantime:

8. Created "messages" module and moved `sayHi` builder there. Also made "Are mods paid?" logic reusable (builder and logic)
9. Made "Why nomination was removed?" message reusable (builder and logic)

---

If you see any variable renaming, in all cases it was done via the IDE automatically, so should not introduce any issues, but to draw your attention to them: `content` was renamed to `decoded` to allow for non-collusive destructuring of `resolvedMsg`, and `randomPlop` & `randomOops` to `getRandomPlop` and `getRandomOops` respectively to indicate that they are "actionable".

I hope the PR will not bring in any issues and if you like the idea - it would be great if we could collaborate on the bot development - I can add tests, features, eventually CI/CD, and, ofc, help debug issues should they arise.

P.S. I apologize for the force-pushes - just noticed that the merge resulted in an issue with variable naming

KR, [Oleg Valter](https://stackoverflow.com/users/11407695/oleg-valter)

### CODE REVIEW

**Comment by samliew** [comment]
Hi @Oaphi, I really appreciate you taking the time to improve the bot.

Your merge request looks great! However, I don't think I will be able to deploy this until the election is over since there are major changes. Hopefully I won't have too many updates to merge with this by the end of the election.

I'll get back to you after the election :)

**Comment by Oaphi** [comment]
Hi Samuel - thank you for responding, glad you like the idea! No worries about the timing - if you are ok with this, I will try to keep up with your updates and resolve conflicts as they go and add extra tests for already existing features - does this sound good?

**Comment by samliew** [comment]
Hey @Oaphi, if you need a room to test the bot in, you can use https://chat.stackoverflow.com/rooms/190503.

Your local .env file should look something like this:

```
ACCOUNT_EMAIL=(email address of bot account)
ACCOUNT_PASSWORD=(password of bot account)
ADMIN_IDS=(your main account user id)
CHAT_DOMAIN=stackoverflow.com
CHAT_ROOM_ID=190503
DEBUG=false
ELECTION_CHATROOM_URL=
ELECTION_PAGE_URL=https://stackoverflow.com/election/12
ELECTION_QA_URL=
MAINTENANCE_PAGE_URL=https://samliew.com/under-maintenance
NODE_ENV=development
PASSWORD=12345678
SCRAPE_INTERVAL_MINS=10
SCRIPT_HOSTNAME=http://localhost
STACK_API_KEY=
THROTTLE_SECS=2
```

**Comment by Oaphi** [comment]
Heya @samliew - thank you for adding me to the repository,

Re: master branch - got it, will be sure to tread carefully! 

Re: room - as soon as I am sure that both the changes and your codebase are sufficiently 
covered with tests, will surely do, and thanks for providing the .env file structure.

P.s. I assume the PR can be closed then to avoid cluttering?

**Comment by Oaphi** [comment]
Samuel, assuming the silence means agreement I am closing this PR and moving to contributing to a separate brunch here as we agreed - looking forward to testing and deploying the polished version after the election ends if we do not encounter any issues 👌.

**Comment by samliew** [comment]
Yes, thanks 👍

**Comment by samliew** [comment]
@Oaphi I'm done with making final bugfixes and moved the bot back to the [development room](https://chat.stackoverflow.com/rooms/190503/electionbot-development). If you can update your branch based on what's currently on the master branch, I'll pull and test it on my end.

**Comment by Oaphi** [comment]
Hi @samliew - if we could defer to the end of the week it would be great, I am usually busy during the week, but will have plenty of time to bring my changes up to date with your most recent updates without rushing things - does this sound good? Btw, congratulations on the end of the election!

**Comment by samliew** [comment]
No rush at all - it's mostly a fun project at this point

**Comment by Oaphi** [comment]
@samliew - thank you, I wanted to start participating in SOBotics prominently, and a useful bot changes to which won't break anything extremely crucial is just what doctor ordered :) Besides, it is indeed a fun project to pour some time in

**Pull request closed without merging**
